"""File parsing and conflict resolution for LLM-generated files."""

import logging
import re
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class GeneratedFile:
    """Represents a file generated by the LLM."""
    filename: str
    content: str


def parse_generated_files(response_text: str) -> list[GeneratedFile]:
    """Parse LLM response text and extract generated files.
    
    Args:
        response_text: Raw text response from the LLM
        
    Returns:
        List of GeneratedFile objects with filename and content
    """
    pattern = r"--- START OUTPUT: (.*?) ---\n(.*?)--- END OUTPUT: \1 ---"
    matches = re.findall(pattern, response_text, re.DOTALL)

    return [
        GeneratedFile(filename=filename.strip(), content=content.strip())
        for filename, content in matches
    ]


def resolve_file_conflicts(files: list[GeneratedFile]) -> list[GeneratedFile]:
    """Resolve filename conflicts in-memory.
    
    - Removes exact duplicates (same filename + content)
    - Renames files with same name but different content (file.1.md, file.2.md)
    - Preserves directory structure
    
    Args:
        files: List of GeneratedFile objects from parsing
        
    Returns:
        List of unique GeneratedFile objects ready to save
    """
    # Track: filename -> list of (content, index in result)
    seen: dict[str, list[tuple[str, int]]] = {}
    result: list[GeneratedFile] = []

    # Statistics
    renamed_count = 0
    skipped_count = 0

    for file in files:
        filename = file.filename
        content = file.content

        if filename not in seen:
            # First occurrence of this filename
            seen[filename] = [(content, len(result))]
            result.append(file)
            logger.debug("Added file: %s", filename)
        else:
            # Filename already seen, check content
            found_duplicate = False

            for seen_content, _ in seen[filename]:
                if seen_content == content:
                    # Exact duplicate (same name + content), skip
                    logger.info("Skipped exact duplicate: %s", filename)
                    skipped_count += 1
                    found_duplicate = True
                    break

            if not found_duplicate:
                # Same name, different content - need to rename
                relative_path = Path(filename)
                parent_dir = relative_path.parent
                base = relative_path.stem
                ext = relative_path.suffix

                # Find next available number
                counter = 1
                while True:
                    new_name = f"{base}.{counter}{ext}"
                    new_filename = (
                        str(parent_dir / new_name)
                        if parent_dir != Path('.')
                        else new_name
                    )

                    # Check if this numbered name already exists in our seen list
                    if new_filename not in seen:
                        seen[new_filename] = [(content, len(result))]
                        result.append(GeneratedFile(filename=new_filename, content=content))
                        logger.info(
                            "Renamed conflicting file: %s -> %s",
                            filename,
                            new_filename
                        )
                        renamed_count += 1
                        break

                    # Check if numbered file has same content
                    is_dup = any(sc == content for sc, _ in seen[new_filename])
                    if is_dup:
                        logger.info(
                            "Skipped duplicate: %s (same as %s)",
                            filename,
                            new_filename
                        )
                        skipped_count += 1
                        found_duplicate = True
                        break

                    counter += 1

    logger.info(
        "Processed %d files → %d unique (%d renamed, %d duplicates skipped)",
        len(files),
        len(result),
        renamed_count,
        skipped_count
    )
    return result
